name: build-test-gosec

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: Build
      run: go build -v ./...
    - name: Test
      run: go test -v ./...
    - name: gosec ./...
      run: | # https://github.com/securego/gosec/issues/469
        export PATH=$PATH:$(go env GOPATH)/bin
        go install github.com/securego/gosec/v2/cmd/gosec@latest
        gosec ./...
